'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Final_WebApp

    Partial Public Class Customer
        Public Property CustNo As Integer
        Public Property CustName As String
        Public Property CustAddress As String
        Public Property PostCode As Integer
        Public Property InterestCode As String
    
        Public Overridable Property Special_Interests As Special_Interests
        Public Overridable Property Sales As ICollection(Of Sale) = New HashSet(Of Sale)
    
    End Class

End Namespace
