'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Final_WebApp

    Partial Public Class Entities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=Entities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property C__RefactorLog() As DbSet(Of C__RefactorLog)
        Public Overridable Property Customers() As DbSet(Of Customer)
        Public Overridable Property Records() As DbSet(Of Record)
        Public Overridable Property Sales() As DbSet(Of Sale)
        Public Overridable Property Special_Interests() As DbSet(Of Special_Interests)
    
    End Class

End Namespace
