'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Final_WebApp

    Partial Public Class Record
        Public Property RecordID As String
        Public Property Title As String
        Public Property Performer As String
    
        Public Overridable Property Sales As ICollection(Of Sale) = New HashSet(Of Sale)
    
    End Class

End Namespace
