'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Final_WebApp

    Partial Public Class Sale
        Public Property SaleDate As Date
        Public Property PricePaid As Decimal
        Public Property RecordID As String
        Public Property CustNo As Integer
    
        Public Overridable Property Customer As Customer
        Public Overridable Property Record As Record
    
    End Class

End Namespace
